[package]
name = "squishyid"
version = "0.1.1"
edition = "2021"
description = "Shorten and obfuscate IDs."
authors = ["Paweł (bbkr) Pabian"]
license = "Artistic-2.0"
repository = "https://github.com/bbkr/SquishyID"
readme = "README.md"

[dependencies]
